---
title: "DiseaseDiva"
author: "Us"
date: "10/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Cleaning Our Data

```{r}
#Load data downloaded from 
rawdat <- read.csv("/Users/parinithakompala/Desktop/QBS181/project/diseasedivadata.csv")
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
#Summarize
summary(rawdat)
```
`
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
#Remove NAs
complete_dat <- na.omit(rawdat)

```


```{r}
#Check for duplicates
duplicated(complete_dat$Sample.ID)

```


```{r}
#Check if sample id is dup
complete_dat[!complete_dat$Patient.ID %in% complete_dat$Sample.ID, ]


```
```{r}
cols_nonunique <- c()

for(i in 1:ncol(complete_dat)){
  if(length(unique(complete_dat[,i])) <= 1){
    cols_nonunique[length(cols_nonunique) + 1] <- i
  }
}

print(cols_nonunique)

```

```{r}

remove_nonuniques <- complete_dat[,-cols_nonunique]


finaldata<-remove_nonuniques

```

Aim(3.1)-Assign classifications of “high”, “medium” or “low” based on the intensity of mutation count
```{r}

range(finaldata$tumor.content) ##checking the range of the content

#fixing thresholds to fixate the Severity levels
finaldata%>%add_column(Severity="Low")->finaldata
finaldata%>%mutate(Severity=ifelse(`tumor.content`>30 & `tumor.content`<=70 ,"Moderate",Severity))->finaldata
finaldata%>%mutate(Severity=ifelse(`tumor.content`>70 & `tumor.content`<=100 ,"High",Severity))->finaldata
unique(finaldata$Severity)

```
Aim3.3-Are these then related to biopsy sites?  (we need to add more to this)
```{r}
finaldata%>%group_by(Severity,`Tumor.Site`)%>%summarise(count=n())#number of subjects in each level
```









